---
exclude:
  - "**/vendor/**/*"
  - "**/node_modules/**/*"
linters:
  ErbSafety:
    enabled: true
    exclude:
      - '**/app/views/kaminari/*'
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
