require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "Rakefile"
    - "config.ru"
    - "spec/**/*"
    # we might need to review all those migrations and create a new one
    # for referential integrity and follow the best practices from rubocop-rails:
    # - https://guides.rubyonrails.org/active_record_migrations.html#active-record-and-referential-integrity
    - "db/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - uat
    - development
    - test

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict   # or 'flexible'

Rails/Date:
  Enabled: true
  EnforcedStyle: strict   # flags Date.current too; use Time.zone.today

Style/DateTime:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - "lib/tasks/reset_extractions.rake"
    - "app/models/job_completion_summary.rb"
    - "app/supplejack/transformation/field_execution.rb"

Metrics/ClassLength:
  Exclude:
    - "app/models/job_completion_summary.rb"
    - "app/supplejack/extraction/execution.rb"
    - "app/supplejack/job_completion_summary_logger.rb"
    - "app/models/job_completion_services/context_builder.rb"

Metrics/MethodLength:
  Exclude:
    - "app/supplejack/extraction/execution.rb"
    - "lib/tasks/reset_extractions.rake"
    - "app/models/job_completion_services/context_builder.rb"
    - "app/models/job_completion_summary.rb"
    - "app/sidekiq/transformation_worker.rb"
    - "app/supplejack/transformation/field_execution.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "app/models/job_completion_summary.rb"

Layout/LineLength:
  Exclude:
    - "app/sidekiq/delete_worker.rb"
    - "app/sidekiq/enrichment_extraction_worker.rb"
    - "app/sidekiq/file_extraction_worker.rb"
    - "app/sidekiq/load_worker.rb"
    - "app/sidekiq/text_extraction_worker.rb"
    - "app/sidekiq/transformation_worker.rb"
    - "app/supplejack/extraction/execution.rb"
    - "app/supplejack/load/execution.rb"
    - "app/supplejack/transformation/field_execution.rb"

Lint/RescueException:
  Exclude:
    - "app/supplejack/transformation/field_execution.rb"
