inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "bin/**/*"
    - "db/schema.rb"
    - "Rakefile"
    - "config.ru"

Style/Documentation:
  Enabled: false
