require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "Rakefile"
    - "config.ru"
    - "spec/**/*"
    # we might need to review all those migrations and create a new one
    # for referential integrity and follow the best practices from rubocop-rails:
    # - https://guides.rubyonrails.org/active_record_migrations.html#active-record-and-referential-integrity
    - "db/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - uat
    - development
    - test

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict   # or 'flexible'

Rails/Date:
  Enabled: true
  EnforcedStyle: strict   # flags Date.current too; use Time.zone.today

Style/DateTime:
  Enabled: true
