inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "Rakefile"
    - "config.ru"
    - "spec/**/*"
    - "db/migrate/*"

Style/Documentation:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - uat
    - development
    - test
