services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./dev_data/mysql:/var/lib/mysql
  redis:
    image: redis
    ports:
      - 6379:6379
